# -----------------------------------------------------------------------------
# Backend Deployment
#
# A Deployment ensures the desired number of backend pods are always running.
# If a pod crashes, Kubernetes automatically recreates it.
# -----------------------------------------------------------------------------

apiVersion: apps/v1
kind: Deployment

metadata:
  name: airace-backend
  labels:
    app: airace-backend

spec:
  replicas: 1

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0

  selector:
    matchLabels:
      app: airace-backend

  template:
    metadata:
      labels:
        app: airace-backend

    spec:
      containers:
        - name: airace-backend

          # Docker image stored in Amazon ECR
          image: ${BACKEND_IMAGE}

          imagePullPolicy: Always

          ports:
            - containerPort: 8000

          # Load AWS credentials from Kubernetes Secret
          envFrom:
            - secretRef:
                name: aws-credentials