# -----------------------------------------------------------------------------
# Frontend Service
#
# Exposes the React UI outside the Kubernetes cluster using an AWS
# Elastic Load Balancer.
# -----------------------------------------------------------------------------

apiVersion: v1
kind: Service

metadata:
  name: airace-frontend

spec:
  selector:
    app: airace-frontend

  type: LoadBalancer

  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000